---
# Repository manager specific configuration
webserver_packages:
  nginx:
    - nginx
    - python3-pip
  apache:
    - httpd
    - python3-pip

webserver_service:
  nginx: nginx
  apache: httpd

webserver_config_path:
  nginx: "/etc/nginx/sites-available"
  apache: "/etc/httpd/conf.d/"

webserver_enabled_path:
  nginx: "/etc/nginx/sites-enabled"
  apache: "/etc/httpd/conf.d/"

# Web server security
webserver_security:
  server_tokens: false
  client_max_body_size: "10M"
  access_log: true
  error_log: true