---
- name: "Ansible Updates Reporting Pipeline"
  hosts: ansible
  gather_facts: true
  become: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_timestamp: "{{ ansible_date_time.epoch }}"
    execution_id: "{{ ansible_date_time.iso8601_basic_short }}"
    # Variable pour contrôler l'utilisation du repository
    use_repository_manager: "{{ groups['repository_managers'] is defined and groups['repository_managers'] | length > 0 }}"
  tasks:
    - name: "(site) Validate repository manager availability"
      ping:
      delegate_to: "{{ groups['repository_managers'][0] }}"
      when: use_repository_manager | bool
      tags: [always, validation]

    - name: "(site) Display repository manager status"
      debug:
        msg: "Repository manager will {{ 'be used' if use_repository_manager else 'NOT be used' }} for this execution"
      tags: [always, info]

    - name: "(site) Set global execution variables"
      set_fact:
        execution_id: "{{ execution_id }}"
        execution_timestamp: "{{ execution_timestamp }}"
        use_repository_manager: "{{ use_repository_manager }}"
      tags: [always, variables]

- name: "Pre-flight Connectivity Check"
  hosts: all:!repository_managers:!localhost:!ansible
  gather_facts: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
  tasks:
    - name: "(connectivity) Test host connectivity"
      ping:
      register: ping_result
      ignore_errors: yes
      ignore_unreachable: yes

    - name: "(connectivity) Set host connectivity status"
      set_fact:
        host_is_reachable: "{{ ping_result.ping is defined and ping_result.ping == 'pong' }}"
        host_connectivity_error: "{{ ping_result.msg | default('Host unreachable') if ping_result.ping is not defined else '' }}"
    
    - name: "(connectivity) Debug ping result for {{ inventory_hostname }}"
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Ping succeeded: {{ ping_result.ping is defined }}
          Unreachable: {{ ping_result.unreachable | default(false) }}
          Failed: {{ ping_result is failed }}
          Is reachable: {{ host_is_reachable }}
        verbosity: 2

    - name: "(connectivity) Create report for unreachable host"
      copy:
        content: |
          {
            "hostname": "{{ inventory_hostname }}",
            "execution_id": "{{ execution_id }}",
            "timestamp": "{{ lookup('pipe', 'date -Iseconds') }}",
            "status": "unreachable",
            "error": "{{ ping_result.msg | default('Host unreachable') }}",
            "updates": {
              "total_count": 0,
              "security_count": 0,
              "packages": [],
              "status": "unreachable"
            }
          }
        dest: "{{ lookup('env', 'AWX_ARTIFACTS_DIR') | default('/tmp/ansible-reports') }}/{{ inventory_hostname }}.json"
        mode: '0644'
      delegate_to: localhost
      become: false
      when: not host_is_reachable
      ignore_errors: yes

- name: "Consolidate Connectivity Results"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  tasks:
    - name: "(connectivity) Build lists of reachable and unreachable hosts"
      set_fact:
        reachable_hosts: "{% set reach = [] %}{% for host in groups['all'] | difference(groups['repository_managers'] | default([])) | difference(['localhost', 'ansible']) %}{% if hostvars[host]['host_is_reachable'] | default(false) %}{% set _ = reach.append(host) %}{% endif %}{% endfor %}{{ reach }}"
        unreachable_hosts: "{% set unreach = [] %}{% for host in groups['all'] | difference(groups['repository_managers'] | default([])) | difference(['localhost', 'ansible']) %}{% if not hostvars[host]['host_is_reachable'] | default(false) %}{% set _ = unreach.append(host) %}{% endif %}{% endfor %}{{ unreach }}"

    - name: "(connectivity) Save connectivity results"
      set_fact:
        connectivity_results:
          reachable_hosts: "{{ reachable_hosts }}"
          unreachable_hosts: "{{ unreachable_hosts }}"
          unreachable_details: "{% set details = [] %}{% for host in unreachable_hosts %}{% set _ = details.append({'hostname': host, 'error_type': 'unreachable', 'error_message': hostvars[host]['host_connectivity_error'] | default('Connection failed'), 'timestamp': lookup('pipe', 'date -Iseconds')}) %}{% endfor %}{{ details }}"
      delegate_to: localhost
      run_once: true

- name: "Display Connectivity Summary"
  hosts: ansible
  gather_facts: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  tasks:
    - name: "(connectivity) Get connectivity results"
      set_fact:
        reachable_hosts: "{{ hostvars['localhost']['connectivity_results']['reachable_hosts'] }}"
        unreachable_hosts: "{{ hostvars['localhost']['connectivity_results']['unreachable_hosts'] }}"
        unreachable_details: "{{ hostvars['localhost']['connectivity_results']['unreachable_details'] }}"

    - name: "(connectivity) Calculate connectivity statistics"
      set_fact:
        total_target_hosts: "{{ groups['all'] | difference(groups['repository_managers'] | default([])) | difference(['localhost', 'ansible']) | length }}"
        total_reachable: "{{ reachable_hosts | length }}"
        total_unreachable: "{{ unreachable_hosts | length }}"

    - name: "(connectivity) Display connectivity summary"
      debug:
        msg: |
          ==========================================
          Connectivity Check Results
          ==========================================
          Total Target Hosts: {{ total_target_hosts }}
          Reachable: {{ total_reachable }}
          Unreachable: {{ total_unreachable }}
          
          {% if total_unreachable | int > 0 %}
          Unreachable Hosts:
          {% for host in unreachable_hosts %}
          - {{ host }}
          {% endfor %}
          {% endif %}
          
          Proceeding with reachable hosts only...
          ==========================================
      tags: [connectivity, summary]

- name: "Setup Repository Manager"
  hosts: repository_managers
  gather_facts: true
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
    use_repository_manager: "{{ hostvars['ansible']['use_repository_manager'] }}"
  tasks:
    - name: "(repository_setup) Execute repository manager role"
      include_role:
        name: repository_manager
      when: use_repository_manager | bool
      tags: [repository, setup]

    - name: "(repository_setup) Generate API endpoints after setup"
      include_tasks: roles/repository_manager/tasks/generate_api_endpoints.yml
      when: use_repository_manager | bool
      tags: [repository, api]

- name: "Collect Updates Information"
  hosts: all:!repository_managers:!localhost:!ansible
  gather_facts: false
  serial: "{{ updates_collection_serial | default('100%') }}"
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
    use_repository_manager: "{{ hostvars['ansible']['use_repository_manager'] }}"
    reachable_hosts: "{{ hostvars['localhost']['connectivity_results']['reachable_hosts'] | default([]) }}"
    # Transmettre l'information aux rôles
    repository_enabled: "{{ use_repository_manager | default(false) }}"
  tasks:
    - name: "(updates_collection) Skip unreachable hosts"
      meta: end_host
      when: inventory_hostname not in reachable_hosts
    
    - name: "(updates_collection) Gather facts for reachable hosts"
      setup:
      when: inventory_hostname in reachable_hosts

    - name: "(updates_collection) Execute updates collector role"
      block:
        - name: "(updates_collection) Include updates collector"
          include_role:
            name: updates_collector
          
        - name: "(updates_collection) Mark host as successful"
          set_fact:
            host_collection_status: "success"
            
      rescue:
        - name: "(updates_collection) Handle collection failure"
          set_fact:
            host_collection_status: "failed"
            collection_error: "{{ ansible_failed_result.msg | default('Collection failed') }}"
            
        - name: "(updates_collection) Create error report for failed host"
          copy:
            content: |
              {
                "hostname": "{{ inventory_hostname }}",
                "execution_id": "{{ execution_id }}",
                "timestamp": "{{ lookup('pipe', 'date -Iseconds') }}",
                "status": "failed",
                "error": "{{ collection_error }}",
                "updates": {
                  "total_count": 0,
                  "security_count": 0,
                  "packages": [],
                  "status": "collection_failed"
                }
              }
            dest: "{{ lookup('env', 'AWX_ARTIFACTS_DIR') | default('/tmp/ansible-reports') }}/{{ inventory_hostname }}.json"
            mode: '0644'
          delegate_to: localhost
          become: false
          ignore_errors: yes
      tags: [collection, updates]

- name: "Generate Consolidated Reports"
  hosts: "{{ groups['repository_managers'] if (groups['repository_managers'] is defined and groups['repository_managers'] | length > 0) else 'localhost' }}"
  gather_facts: true
  become: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
    use_repository_manager: "{{ hostvars['ansible']['use_repository_manager'] }}"
    repository_enabled: "{{ use_repository_manager | default(false) }}"
    reachable_hosts: "{{ hostvars['localhost']['connectivity_results']['reachable_hosts'] | default([]) }}"
    unreachable_hosts: "{{ hostvars['localhost']['connectivity_results']['unreachable_hosts'] | default([]) }}"
    unreachable_details: "{{ hostvars['localhost']['connectivity_results']['unreachable_details'] | default([]) }}"
  tasks:
    - name: "(report_generation) Execute report generator role"
      include_role:
        name: report_generator
      vars:
        include_unreachable_hosts: true
      ignore_errors: yes
      tags: [reporting, generation]

- name: "Update Repository Indexes and APIs"
  hosts: repository_managers
  gather_facts: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
    use_repository_manager: "{{ hostvars['ansible']['use_repository_manager'] }}"
  tasks:
    - name: "(repository_final_update) Force regeneration of all indexes and APIs"
      include_tasks: roles/repository_manager/tasks/generate_indexes.yml
      when: use_repository_manager | bool
      tags: [repository, final_update, indexes]

- name: "Send Notifications"
  hosts: "{{ groups['repository_managers'] if (groups['repository_managers'] is defined and groups['repository_managers'] | length > 0) else 'localhost' }}"
  gather_facts: false
  vars_files:
    - vars/ansible-updates-reporting.yml
  vars:
    execution_id: "{{ hostvars['ansible']['execution_id'] }}"
    execution_timestamp: "{{ hostvars['ansible']['execution_timestamp'] }}"
    use_repository_manager: "{{ hostvars['ansible']['use_repository_manager'] }}"
    repository_enabled: "{{ use_repository_manager | default(false) }}"
  tasks:
    - name: "(notification) Execute notification manager role"
      include_role:
        name: notification_manager
      when: 
        - send_notifications | default(true) | bool
        - smtp_server is defined
      tags: [notification, email]