---
- name: "(send_webhook) Prepare webhook payload"
  set_fact:
    webhook_payload:
      execution_id: "{{ execution_id }}"
      timestamp: "{{ ansible_date_time.iso8601 }}"
      summary: "{{ consolidated_data.summary }}"
      critical_hosts: "{{ consolidated_data.critical_hosts | length }}"
      priority: "{{ 'HIGH' if consolidated_data.summary.total_security_updates > security_thresholds.critical_updates else 'MEDIUM' if consolidated_data.summary.total_security_updates > 0 else 'LOW' }}"
  tags: [notification, webhook, prepare]

- name: "(send_webhook) Send webhook notification"
  uri:
    url: "{{ webhook_url }}"
    method: POST
    body_format: json
    body: "{{ webhook_payload }}"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ webhook_token | default('') }}"
    status_code: [200, 201, 202]
  tags: [notification, webhook, send]