---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'

ansible_config: '../ansible-awx-ssh.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend:
    - RUN echo "Setting up custom SSH configuration"
  append:
    - RUN mkdir -p /home/runner/.ssh && chmod 700 /home/runner/.ssh
    - COPY ansible-awx-ssh.cfg /home/runner/.ansible.cfg