---
# AWX Data Collector Main Tasks

- name: "(awx_data_collector) Include AWX mode variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - awx_mode.yml
      paths:
        - "{{ playbook_dir }}/vars"
      skip: true
  tags: [awx, setup]

- name: "(awx_data_collector) Display execution mode"
  debug:
    msg: "Running in {{ 'AWX/Tower' if is_awx_environment else 'Standard Ansible' }} mode"
  run_once: true
  tags: [awx, debug]

- name: "(awx_data_collector) Setup artifact directories in AWX mode"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ reports_storage_path }}"
    - "{{ host_reports_path }}"
    - "{{ consolidated_reports_path }}"
    - "{{ temp_storage_path }}"
  when: is_awx_environment
  delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
  run_once: true
  tags: [awx, setup, directories]

- name: "(awx_data_collector) Collect host update data"
  set_fact:
    host_updates_data:
      hostname: "{{ inventory_hostname }}"
      ansible_host: "{{ ansible_host | default(inventory_hostname) }}"
      os_family: "{{ ansible_os_family }}"
      distribution: "{{ ansible_distribution }}"
      distribution_version: "{{ ansible_distribution_version }}"
      updates: "{{ collected_updates | default({}) }}"
      collection_timestamp: "{{ ansible_date_time.iso8601 }}"
      execution_id: "{{ execution_id | default(awx_job_id) }}"
      requires_reboot: "{{ requires_reboot | default(false) }}"
    cacheable: "{{ use_cacheable_facts }}"
  tags: [awx, collection, facts]

- name: "(awx_data_collector) Store data as AWX artifact"
  block:
    - name: "(awx_data_collector) Create host data artifact file"
      copy:
        content: "{{ host_updates_data | to_nice_json }}"
        dest: "{{ host_reports_path }}/{{ inventory_hostname }}_data.json"
        mode: '0644'
      delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
      
    - name: "(awx_data_collector) Register artifact in AWX stats"
      set_stats:
        data:
          artifacts:
            host_data_files: "{{ artifacts.host_data_files | default([]) + [host_reports_path + '/' + inventory_hostname + '_data.json'] }}"
            total_hosts_collected: "{{ artifacts.total_hosts_collected | default(0) + 1 }}"
        per_host: false
        aggregate: true
      when: use_set_stats
  when: enable_awx_artifacts
  tags: [awx, artifacts, storage]

- name: "(awx_data_collector) Report host summary to AWX stats"
  set_stats:
    data:
      host_summaries:
        "{{ inventory_hostname }}":
          total_updates: "{{ collected_updates.total_count | default(0) }}"
          security_updates: "{{ collected_updates.security_count | default(0) }}"
          requires_reboot: "{{ requires_reboot | default(false) }}"
    per_host: false
    aggregate: true
  when: 
    - report_to_stats
    - collected_updates is defined
  tags: [awx, stats, summary]

- name: "(awx_data_collector) Store data using traditional method for non-AWX"
  block:
    - name: "(awx_data_collector) Ensure local storage directory exists"
      file:
        path: "{{ local_reports_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      
    - name: "(awx_data_collector) Write host data to local file"
      copy:
        content: "{{ host_updates_data | to_nice_json }}"
        dest: "{{ local_reports_path }}/{{ inventory_hostname }}.json"
        mode: '0644'
      delegate_to: localhost
  when: 
    - not is_awx_environment
    - maintain_backward_compatibility | default(true)
  tags: [local, storage, compatibility]

- name: "(awx_data_collector) Include aggregation tasks"
  include_tasks: aggregate_data.yml
  when:
    - inventory_hostname == groups['all'][-1]
    - enable_awx_artifacts
  tags: [awx, aggregation]