---
- name: "(repository_manager) Include OS detection tasks"
  include_tasks: detect_os.yml
  tags: [detection, os]

- name: "(repository_manager) Include initialization check tasks"
  include_tasks: check_initialization.yml
  tags: [initialization, check]

- name: "(repository_manager) Include setup directories tasks"
  include_tasks: setup_directories.yml
  when: not repository_already_initialized | bool
  tags: [setup, directories]

- name: "(repository_manager) Include webserver configuration tasks"
  include_tasks: configure_webserver.yml
  when: not repository_already_initialized | bool
  tags: [setup, webserver]

- name: "(repository_manager) Include initialization marker tasks"
  include_tasks: mark_initialized.yml
  when: not repository_already_initialized | bool
  tags: [initialization, marker]

- name: "(repository_manager) Include index generation tasks"
  include_tasks: generate_indexes.yml
  tags: [indexes, generation]

- name: "(repository_manager) Include JSON validation tasks"
  include_tasks: validate_json_apis.yml
  tags: [validation, json]

- name: "(repository_manager) Include cleanup tasks"
  include_tasks: cleanup_reports.yml
  tags: [cleanup, maintenance]