---
- name: "(repository_manager) Include setup directories tasks"
  include_tasks: setup_directories.yml
  tags: [setup, directories]

- name: "(repository_manager) Include webserver configuration tasks"
  include_tasks: configure_webserver.yml
  tags: [setup, webserver]

- name: "(repository_manager) Include cleanup tasks"
  include_tasks: cleanup_reports.yml
  tags: [cleanup, maintenance]