---
- name: "(setup_directories) Ensure base directory parent exists"
  file:
    path: "{{ repository_base_path | dirname }}"
    state: directory
    mode: '0755'
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create base repository directory"
  file:
    path: "{{ repository_base_path }}"
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create report format base directories"
  file:
    path: "{{ repository_base_path }}/{{ item }}"
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  loop: "{{ report_formats }}"
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create archives directory for each format"
  file:
    path: "{{ repository_base_path }}/{{ item }}/archive"
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  loop: "{{ report_formats }}"
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create log directory for repository"
  file:
    path: "{{ repository_base_path }}/logs"
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create assets directory for CSS/JS"
  file:
    path: "{{ repository_base_path }}/assets"
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  become: true
  tags: [setup, directories]

- name: "(setup_directories) Create main index.html for repository root"
  template:
    src: main_index.html.j2
    dest: "{{ repository_base_path }}/index.html"
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
  become: true
  tags: [setup, directories, index]

- name: "(setup_directories) Create format-specific index files"
  template:
    src: format_index.html.j2
    dest: "{{ repository_base_path }}/{{ item }}/index.html"
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
  loop: "{{ report_formats }}"
  become: true
  vars:
    format_type: "{{ item }}"
  tags: [setup, directories, index]