---
# AWX-Compatible Report Generation Tasks

- name: "(awx_reports) Include AWX mode variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - awx_mode.yml
      paths:
        - "{{ playbook_dir }}/vars"
      skip: true
  tags: [awx, setup]

- name: "(awx_reports) Gather consolidated data from facts"
  set_fact:
    consolidated_data: "{{ hostvars[inventory_hostname]['consolidated_data'] | default(consolidated_data) }}"
  when: consolidated_data is not defined
  tags: [awx, data]

- name: "(awx_reports) Generate JSON report in AWX mode"
  block:
    - name: "(awx_reports) Create JSON report"
      copy:
        content: "{{ consolidated_data | to_nice_json }}"
        dest: "{{ reports_storage_path }}/report_{{ awx_job_id }}.json"
        mode: '0644'
      delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
      
    - name: "(awx_reports) Register JSON report as artifact"
      set_stats:
        data:
          artifacts:
            json_report: "{{ reports_storage_path }}/report_{{ awx_job_id }}.json"
        per_host: false
      when: use_set_stats
  when: 
    - is_awx_environment
    - "'json' in report_formats"
  tags: [awx, reports, json]

- name: "(awx_reports) Generate HTML report in AWX mode"
  block:
    - name: "(awx_reports) Create HTML report from template"
      template:
        src: consolidated_report.html.j2
        dest: "{{ reports_storage_path }}/report_{{ awx_job_id }}.html"
        mode: '0644'
      delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
      
    - name: "(awx_reports) Register HTML report as artifact"
      set_stats:
        data:
          artifacts:
            html_report: "{{ reports_storage_path }}/report_{{ awx_job_id }}.html"
        per_host: false
      when: use_set_stats
  when:
    - is_awx_environment
    - "'html' in report_formats"
  tags: [awx, reports, html]

- name: "(awx_reports) Generate Excel report in AWX mode"
  block:
    - name: "(awx_reports) Check container runtime availability"
      command: "{{ container_runtime }} --version"
      register: container_check
      failed_when: false
      changed_when: false
      delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
      
    - name: "(awx_reports) Generate Excel using container"
      include_tasks: awx_excel_container.yml
      when: 
        - container_check.rc == 0
        - use_containerized_excel
        
    - name: "(awx_reports) Fallback to CSV generation"
      include_tasks: generate_csv_fallback.yml
      when: container_check.rc != 0 or not use_containerized_excel
  when:
    - is_awx_environment
    - "'excel' in report_formats"
  tags: [awx, reports, excel]

- name: "(awx_reports) Create report index"
  block:
    - name: "(awx_reports) Generate report index data"
      set_fact:
        report_index:
          execution_id: "{{ awx_job_id }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          reports_generated: "{{ report_formats }}"
          summary: "{{ consolidated_data.summary }}"
          artifacts:
            json: "{{ reports_storage_path }}/report_{{ awx_job_id }}.json"
            html: "{{ reports_storage_path }}/report_{{ awx_job_id }}.html"
            excel: "{{ reports_storage_path }}/report_{{ awx_job_id }}.xlsx"
      
    - name: "(awx_reports) Write report index"
      copy:
        content: "{{ report_index | to_nice_json }}"
        dest: "{{ reports_storage_path }}/index_{{ awx_job_id }}.json"
        mode: '0644'
      delegate_to: "{{ 'localhost' if not disable_localhost_delegation else omit }}"
      
    - name: "(awx_reports) Register report index as artifact"
      set_stats:
        data:
          artifacts:
            report_index: "{{ reports_storage_path }}/index_{{ awx_job_id }}.json"
            all_reports: "{{ report_index.artifacts }}"
        per_host: false
      when: use_set_stats
  when: is_awx_environment
  tags: [awx, reports, index]

- name: "(awx_reports) Report generation summary"
  set_stats:
    data:
      report_generation:
        status: "completed"
        formats_generated: "{{ report_formats }}"
        total_hosts: "{{ consolidated_data.summary.total_hosts }}"
        critical_issues: "{{ consolidated_data.security_analysis.critical_hosts | length }}"
    per_host: false
  when:
    - is_awx_environment
    - use_set_stats
  tags: [awx, stats, summary]