---
- name: "(report_generator) Include repository-based data aggregation"
  include_tasks: aggregate_data.yml
  when: use_repository_manager | default(false) | bool
  tags: [aggregation, data, repository]

- name: "(report_generator) Include local data aggregation"
  include_tasks: aggregate_local_data.yml
  when: not (use_repository_manager | default(false) | bool)
  tags: [aggregation, data, local]

- name: "(report_generator) Include JSON report generation"
  include_tasks: generate_json.yml
  when: "'json' in report_formats"
  tags: [generation, json]

- name: "(report_generator) Include HTML report generation"
  include_tasks: generate_html.yml
  when: "'html' in report_formats"
  tags: [generation, html]

- name: "(report_generator) Include Excel report generation"
  include_tasks: generate_excel.yml
  when: "'excel' in report_formats"
  tags: [generation, excel]

- name: "(report_generator) Display report generation summary"
  debug:
    msg: |
      Report generation completed:
      - Storage type: {{ 'Repository Manager' if use_repository_manager else 'Local' }}
      - Formats: {{ report_formats | join(', ') }}
      - Location: {{ repository_base_path if use_repository_manager else local_reports_path }}
  tags: [generation, summary]