---
- name: "(report_generator) Include setup variables tasks"
  include_tasks: setup_variables.yml
  tags: [setup, variables]

- name: "(report_generator) Include data aggregation tasks"
  include_tasks: aggregate_data.yml
  tags: [aggregation, data]

- name: "(report_generator) Include JSON report generation"
  include_tasks: generate_json.yml
  when: "'json' in report_formats"
  tags: [generation, json]

- name: "(report_generator) Include HTML report generation"
  include_tasks: generate_html.yml
  when: "'html' in report_formats"
  tags: [generation, html]

- name: "(report_generator) Include Excel report generation"
  include_tasks: generate_excel.yml
  when: "'excel' in report_formats"
  tags: [generation, excel]

- name: "(report_generator) Include transfer to repository tasks"
  include_tasks: transfer_to_repository.yml
  when: use_repository_manager | default(false) | bool
  tags: [transfer, repository]

- name: "(report_generator) Display report generation summary"
  debug:
    msg: |
      Report generation completed:
      - Storage type: {{ 'Repository Manager' if use_repository_manager else 'Local Control Node' }}
      - Formats: {{ report_formats | join(', ') }}
      - Control node location: {{ control_node_reports_path }}
      - Repository location: {{ repository_base_path if use_repository_manager else 'N/A' }}
      - Total hosts processed: {{ aggregated_data.summary.total_hosts }}
      - Hosts with errors: {{ aggregated_data.summary.hosts_with_errors }}
  tags: [generation, summary]