---
# Correctif pour synchroniser les execution_id et URLs
# roles/report_generator/tasks/transfer_to_repository.yml - SECTION À CORRIGER

- name: "(transfer_to_repository) Use consistent execution_id for directory naming"
  set_fact:
    transfer_timestamp: "{{ execution_id }}"  # CHANGEMENT: Utiliser execution_id au lieu de ansible_date_time.iso8601_basic_short
  delegate_to: "{{ groups['repository_managers'][0] }}"
  run_once: true
  tags: [transfer, timestamp]

- name: "(transfer_to_repository) Create timestamped directories for each format"
  file:
    path: "{{ repository_base_path }}/{{ item }}/{{ execution_id }}"  # CHANGEMENT: Utiliser execution_id
    state: directory
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0755'
  loop: "{{ report_formats }}"
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  tags: [transfer, directories]

- name: "(transfer_to_repository) Transfer JSON reports to timestamped directory"
  copy:
    src: "{{ control_node_reports_path }}/json/"
    dest: "{{ repository_base_path }}/json/{{ execution_id }}/"  # CHANGEMENT: Utiliser execution_id
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
    backup: false
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  when: "'json' in report_formats"
  tags: [transfer, json]

- name: "(transfer_to_repository) Transfer HTML reports to timestamped directory"
  copy:
    src: "{{ control_node_reports_path }}/html/"
    dest: "{{ repository_base_path }}/html/{{ execution_id }}/"  # CHANGEMENT: Utiliser execution_id
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
    backup: false
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  when: "'html' in report_formats"
  tags: [transfer, html]

- name: "(transfer_to_repository) Transfer Excel reports to timestamped directory"
  copy:
    src: "{{ control_node_reports_path }}/excel/"
    dest: "{{ repository_base_path }}/excel/{{ execution_id }}/"  # CHANGEMENT: Utiliser execution_id
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
    backup: false
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  when: "'excel' in report_formats"
  tags: [transfer, excel]

- name: "(transfer_to_repository) Generate enhanced HTML index for timestamped directory"
  template:
    src: timestamped_html_index.html.j2
    dest: "{{ repository_base_path }}/html/{{ execution_id }}/index.html"  # CHANGEMENT: Utiliser execution_id
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    mode: '0644'
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  when: "'html' in report_formats"
  vars:
    transfer_timestamp: "{{ execution_id }}"  # CHANGEMENT: Passer execution_id au template
  tags: [transfer, html, index]

- name: "(transfer_to_repository) Create symbolic links to latest reports"
  file:
    src: "{{ repository_base_path }}/{{ item }}/{{ execution_id }}"  # CHANGEMENT: Utiliser execution_id
    dest: "{{ repository_base_path }}/{{ item }}/latest"
    state: link
    owner: "{{ current_webserver_user | default('www-data') }}"
    group: "{{ current_webserver_group | default('www-data') }}"
    force: true
  loop: "{{ report_formats }}"
  delegate_to: "{{ groups['repository_managers'][0] }}"
  become: true
  run_once: true
  tags: [transfer, symlinks]