---
- name: "(collect_debian_updates) Set locale to English for consistent parsing"
  set_fact:
    debian_locale_env:
      LC_ALL: "C"
      LANG: "C"
      DEBIAN_FRONTEND: "noninteractive"
  tags: [debian, locale]

- name: "(collect_debian_updates) Update package cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [debian, cache_update]

- name: "(collect_debian_updates) Get list of upgradable packages with English locale"
  shell: |
    LC_ALL=C LANG=C apt list --upgradable 2>/dev/null | grep -v '^Listing' | grep -v '^WARNING'
  register: debian_upgradable_raw
  changed_when: false
  failed_when: false
  tags: [debian, package_list]

- name: "(collect_debian_updates) Fallback: Get list using apt-get simulation"
  shell: |
    LC_ALL=C LANG=C DEBIAN_FRONTEND=noninteractive apt-get upgrade -s 2>/dev/null | grep "^Inst" | sed 's/^Inst //'
  register: debian_upgradable_sim
  changed_when: false
  failed_when: false
  tags: [debian, package_list, fallback]

- name: "(collect_debian_updates) Get security updates using unattended-upgrades"
  shell: |
    if command -v unattended-upgrade >/dev/null 2>&1; then
      LC_ALL=C unattended-upgrade --dry-run 2>/dev/null | grep "^Get:" || echo ""
    else
      echo ""
    fi
  register: debian_security_check
  changed_when: false
  failed_when: false
  tags: [debian, security_check]

- name: "(collect_debian_updates) Get security updates from apt-get simulation"
  shell: |
    LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get upgrade -s 2>/dev/null | grep "^Inst" | grep -E "(security|security-updates)" || echo ""
  register: debian_security_raw
  changed_when: false
  failed_when: false
  tags: [debian, security_direct]

- name: "(collect_debian_updates) Debug raw output"
  debug:
    msg: |
      Raw outputs for debugging:
      Method 1 (apt list): {{ debian_upgradable_raw.stdout_lines | length }} lines
      Method 2 (apt-get sim): {{ debian_upgradable_sim.stdout_lines | length }} lines
      Security check: {{ debian_security_check.stdout_lines | length }} lines
      Security raw: {{ debian_security_raw.stdout_lines | length }} lines
      
      First 3 lines from apt list (English):
      {% for line in debian_upgradable_raw.stdout_lines[:3] %}
      - {{ line }}
      {% endfor %}
  tags: [debian, debug]

- name: "(collect_debian_updates) Parse upgradable packages using primary method"
  set_fact:
    debian_updates: "{{ debian_upgradable_raw.stdout_lines | default([]) | debian_parse_updates }}"
  tags: [debian, parsing]

- name: "(collect_debian_updates) Fallback: Parse using apt-get simulation if primary method failed"
  set_fact:
    debian_updates: "{{ debian_upgradable_sim.stdout_lines | default([]) | debian_parse_apt_get_sim }}"
  when: debian_updates | length == 0 and debian_upgradable_sim.stdout_lines | length > 0
  tags: [debian, parsing, fallback]

- name: "(collect_debian_updates) Enhance security detection"
  set_fact:
    debian_updates_with_security: "{{ debian_updates | debian_enhance_security_detection(debian_security_raw.stdout_lines | default([])) }}"
  tags: [debian, security_enhancement]

- name: "(collect_debian_updates) Count security updates"
  set_fact:
    debian_security_updates_count: "{{ debian_updates_with_security | selectattr('is_security', 'equalto', true) | list | length }}"
  tags: [debian, security_count]

- name: "(collect_debian_updates) Display parsing results"
  debug:
    msg: |
      Debian Updates Parsing Results:
      - Total packages for update: {{ debian_updates_with_security | length }}
      - Security packages: {{ debian_security_updates_count }}
      - Security packages list: {{ debian_updates_with_security | selectattr('is_security', 'equalto', true) | map(attribute='name') | list }}
      - Packages requiring reboot: {{ debian_updates_with_security | selectattr('requires_reboot', 'equalto', true) | map(attribute='name') | list }}
      - Sample packages (first 3):
      {% for pkg in debian_updates_with_security[:3] %}
        * {{ pkg.name }}: {{ pkg.current_version }} → {{ pkg.available_version }} ({{ pkg.repository }})
      {% endfor %}
  when: debian_updates_with_security | length > 0
  tags: [debian, debug]

- name: "(collect_debian_updates) Set collected updates for this host"
  set_fact:
    collected_updates:
      total_count: "{{ debian_updates_with_security | length }}"
      security_count: "{{ debian_security_updates_count }}"
      packages: "{{ debian_updates_with_security }}"
      collection_method: "apt"
      collection_timestamp: "{{ ansible_date_time.iso8601 }}"
      debug_info:
        raw_lines_processed: "{{ debian_upgradable_raw.stdout_lines | length }}"
        fallback_used: "{{ debian_upgradable_raw.stdout_lines | length == 0 }}"
        security_sources: "{{ debian_security_raw.stdout_lines | length }}"
        parsing_method: "{{ 'apt_list' if debian_upgradable_raw.stdout_lines | length > 0 else 'apt_get_simulation' }}"
  tags: [debian, results]