---
- name: "(generate_local_report) Create local reports directory"
  file:
    path: "{{ local_reports_path }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true
  tags: [generation, local, setup]

- name: "(generate_local_report) Generate local JSON report for this host"
  template:
    src: host_report.json.j2
    dest: "{{ local_reports_path }}/{{ inventory_hostname }}.json"
    mode: '0644'
  delegate_to: localhost
  tags: [generation, local, json]

- name: "(generate_local_report) Display local report location"
  debug:
    msg: "Local report generated at: {{ local_reports_path }}/{{ inventory_hostname }}.json"
  tags: [generation, local, info]

- name: "(generate_local_report) Set fact for local report path"
  set_fact:
    host_report_path: "{{ local_reports_path }}/{{ inventory_hostname }}.json"
    report_storage_type: "local"
  tags: [generation, local, facts]