---
- name: "(updates_collector) Include OS detection tasks"
  include_tasks: detect_os.yml
  tags: [detection, os]

- name: "(updates_collector) Include Debian/Ubuntu updates collection"
  include_tasks: collect_debian_updates.yml
  when: ansible_os_family == "Debian"
  tags: [collection, debian, ubuntu]

- name: "(updates_collector) Include RedHat/CentOS/Rocky/Alma updates collection"
  include_tasks: collect_redhat_updates.yml
  when: ansible_os_family == "RedHat"
  tags: [collection, redhat, centos, rocky, alma]

- name: "(updates_collector) Include SUSE updates collection"
  include_tasks: collect_suse_updates.yml
  when: ansible_os_family == "Suse"
  tags: [collection, suse, opensuse]

- name: "(updates_collector) Include repository-based host report generation"
  include_tasks: generate_host_report.yml
  when: 
    - use_repository_manager | default(false) | bool
    - groups['repository_managers'] is defined
    - groups['repository_managers'] | length > 0
  tags: [generation, host_report, repository]

- name: "(updates_collector) Include local host report generation"
  include_tasks: generate_local_report.yml
  when: not (use_repository_manager | default(false) | bool)
  tags: [generation, host_report, local]